# Generated by Django 4.2.7 on 2024-04-01 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequirementDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_customer', models.CharField(blank=True, max_length=100, null=True)),
                ('r_order_startdate', models.DateField(blank=True, null=True)),
                ('r_order_depdate', models.DateField(blank=True, null=True)),
                ('r_order_enddate', models.DateField(blank=True, null=True)),
                ('r_order_loc', models.CharField(blank=True, max_length=100, null=True)),
                ('r_category', models.CharField(blank=True, max_length=100, null=True)),
                ('r_subcategory', models.CharField(blank=True, max_length=100, null=True)),
                ('r_description', models.CharField(blank=True, max_length=100, null=True)),
                ('r_brand', models.CharField(blank=True, max_length=100, null=True)),
                ('r_modelno', models.CharField(blank=True, max_length=100, null=True)),
                ('r_serialno', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
