# Generated by Django 4.2.7 on 2024-04-03 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0002_requirementdetail_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirementdetail',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
