# Generated by Django 4.2.7 on 2024-04-04 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0003_alter_requirementdetail_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirementdetail',
            name='area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='requirementdetail',
            name='asset_tag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='requirementdetail',
            name='box_number',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='requirementdetail',
            name='fc_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='requirementdetail',
            name='mapping',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='requirementdetail',
            name='relation',
            field=models.IntegerField(choices=[(101, 'Parent'), (102, 'Child')], default=101),
        ),
        migrations.AddField(
            model_name='requirementdetail',
            name='sku',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='requirementdetail',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
