# Generated by Django 4.2.7 on 2024-03-07 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='order_status',
            field=models.IntegerField(choices=[(1, 'Booked'), (2, 'Approved'), (3, 'Cancelled'), (4, 'Dispatched')], default=1),
        ),
    ]
