# Generated by Django 4.2.7 on 2024-03-20 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_poc_at_venue_email_orderdetail_maker_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='approver_email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='checker_email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
